version: '3.3'

services:
  database-wsl:
    image: mysql
    volumes:
      - database-wsl_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: "Asia/Bangkok"
      MYSQL_ROOT_PASSWORD: rootci4
      MYSQL_PASSWORD: rootci4
    ports:
      - 33062:3306
    
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    
    
volumes:
  database-wsl_data: {}

