# mysql pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wsl-pvc-db
  namespace: test
  labels:
    app: database-wsl
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  

#mysql service
---
apiVersion: v1
kind: Service
metadata:
  name: database-wsl # host
  namespace: test
  labels:
    app: database-wsl
spec:
  ports:
  - name: wsl-db-port
    port: 3306
    targetPort: 3306
  selector:
    app: database-wsl
    

#mysql deployment
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: database-wsl
  namespace: test
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: database-wsl   
  strategy:
    type: Recreate
  template: 
    metadata: 
      labels: 
        app: database-wsl      
    spec:
      containers:
       - image: mariadb:latest
         name: database-wsl-cont
         env:
         - name: MYSQL_DATABASE
           value: "ci4"
         - name: MYSQL_PASSWORD
           value: "rootci4"
         - name: MYSQL_ROOT_PASSWORD
           value: "rootci4"
         - name: MYSQL_USER
           value: "root"
         resources: {}
            #limits:
            #  cpu: 800m # the CPU limit is define in milicore (m)
            #  memory: 800Mi # the Memory is define in Mebibytes (Mi)
            #requests:
            #  cpu: 500m
         ports:
         - containerPort: 3306
         volumeMounts:
         - name: wsl-volume
           mountPath: /var/lib/mysql
      volumes:
      - name: wsl-volume
        persistentVolumeClaim:
          claimName: wsl-pvc-db

status: {}
