######################################################
# Configmaps: Create Multiples Configmaps data
######################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service_name }}-bootstrap-cm-{{ .Values.targetEnv }}
  namespace: {{ .Values.targetNS }}
data:
    wslbootstrap.sh: |
        #!/bin/bash
        set -x
        echo "Workstation Bootstrap Script"
        echo "==========================="
        cp /tmp/secrets/.env /var/www/html/.env
        FILE=/var/www/html/.env
        if test -f "$FILE"; then
            echo "$FILE exists."
            echo "==========================="
            echo "Workstation Bootstrap Script Copied"
            echo "==========================="
        fi
            echo "Starting Workstation"
            echo "==========================="
            php -v
        echo "==========================="
        yes | composer update
        chmod 777 -R /var/www/html/writable/
        chmod 777 -R /var/www/html/writable/cache/
        chmod 777 -R /var/www/html/writable/session/
        APP_RELEASE_NOTES_DOC_URL="https://localhost:{{ .Values.svcAccessPort }}"
        export APP_RELEASE_NOTES_DOC_URL=$APP_RELEASE_NOTES_DOC_URL
        DATE_GEN_VERSION=$(date +"%Y%m%d%I%M%S")
        export DATE_GEN_VERSION=$(date +"%Y%m%d%I%M%S")
        echo APP_DEPLOYED_AT=$DATE_GEN_VERSION >> $FILE
        echo APP_ENVIRONMENT="{{ .Values.targetEnv }}" >> $FILE
        echo APP_RELEASE_NOTES_DOC_URL=$APP_RELEASE_NOTES_DOC_URL >> $FILE
        echo DYNAMIC_SCRIPTS_PATH=/tmp >> $FILE
        echo "==========================="
        echo "Copy apache config file for Workstation"
        cp /tmp/configmap/workstation.conf /etc/apache2/sites-available/000-default.conf
        echo "==========================="
        echo "Restart apache2"
        apachectl graceful
        #apachectl restart
        # a2ensite 000-default
        # service apache2 reload
        echo "==========================="
    workstation.conf: |
        <VirtualHost *:80>
            ServerAdmin webmaster@localhost
            DocumentRoot /var/www/html/public
            DirectoryIndex index.html index.php
            ServerName {{ .Values.targetEnv }}-my.workstation.co.uk
                <Directory /var/www/html/public>
                        AllowOverride all
                </Directory>
        </VirtualHost>
        ServerName 127.0.0.1