apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsl-{{ .Values.targetEnv }}
  namespace: {{ .Values.targetNS }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wsl-{{ .Values.targetEnv }}
  template:
    metadata:
      labels:
        app: wsl-{{ .Values.targetEnv }}
    spec:
      containers:
        - name: wsl-{{ .Values.targetEnv }}
          image: {{ .Values.targetImage }}:{{ .Values.targetImageTag }}
          ports:
            - containerPort: 80
          env:
            - name: "NGINX_CONFDIR"
              value: "/etc/nginx"
            - name: "NGINX_DOCUMENT_ROOT"
              value: "/var/www/html/public"
            - name: "NGINX_ENVVARS"
              value: "/etc/nginx/envvars"
            - name: "NGINX_RUN_DIR"
              value: "/var/run/nginx"
            # - name: DYNAMIC_SCRIPTS_PATH
            #   value: "/var/www/html/writable"
            - name: DYNAMIC_SCRIPTS_PATH
              value: "/tmp"
            - name: NGINX_RUN_USER
              value: "www-data"
            - name: NGINX_RUN_GROUP
              value: "www-data"
            - name: NGINX_PID_FILE
              value: "/var/run/nginx.pid"
            - name: NGINX_RUN_DIR
              value: "/var/run/nginx"
            - name: NGINX_LOG_DIR
              value: "/var/log/nginx"
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "stat -c %a /tmp && ls -la /tmp && cp /tmp/configmap/wslbootstrap.sh /usr/local/bin/wslbootstrap.sh && chmod +x /usr/local/bin/wslbootstrap.sh && sh /usr/local/bin/wslbootstrap.sh"]
          volumeMounts:      
            - name: {{ .Values.service_name }}-bootstrap-cm-vol
              mountPath: /tmp/configmap
            - name: wslenv-vol-{{ .Values.targetEnv }}
              mountPath: /tmp/secrets
              # `bootstrap` mount bash script from configmap {{ .Values.service_name }}-bootstrap-cm-{{ .Values.targetEnv }}
              # execute in the poststrat lifecycle hook

      volumes:
        - name: {{ .Values.service_name }}-bootstrap-cm-vol
          # Populate the volume with config map data
          configMap:
            # `name` here must match the name 
            # specified in the ConfigMap's YAML 
           name: {{ .Values.service_name }}-bootstrap-cm-{{ .Values.targetEnv }}
        - name: wslenv-vol-{{ .Values.targetEnv }}
          secret:
            secretName: wsl-secret-{{ .Values.targetEnv }}
            items:
            - key: env_file
              path: .env  